import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/home.module.css';
import Nav from '../components/Nav';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Nav />
        <main className={styles.main}>
          <h1>Accueil</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            Perferendis asperiores officia facilis numquam ullam dolor quis
            assumenda fuga provident odio placeat nisi, esse ea exercitationem
            debitis quo nihil porro. Provident!
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            Perferendis asperiores officia facilis numquam ullam dolor quis
            assumenda fuga provident odio placeat nisi, esse ea exercitationem
            debitis quo nihil porro. Provident!
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit.
            Perferendis asperiores officia facilis numquam ullam dolor quis
            assumenda fuga provident odio placeat nisi, esse ea exercitationem
            debitis quo nihil porro. Provident!
          </p>
        </main>
      </div>
    </div>
  );
};

export default Home;
